version: "3.8"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # persist models
    restart: unless-stopped

  lightrag:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - WORKING_DIR=/app/src/kol_zchut_rag_storage_1000_v3
    depends_on:
      - ollama
    command: ["python", "src/query.py"]

volumes:
  ollama_models:
